
SELECT * FROM users
/*
CREATE TABLE IF NOT EXISTS users (
    id TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
PRIMARY KEY (id)

) WITHOUT ROWID
*/